
name: Stable build

on:
  push:
    branches: [ "main" ]

jobs:

  build-amd64:
    name: Build for Windows x64
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Build the project
    - name: Build
      run: dotnet build EFI-Runner/EFI-Runner.csproj -c Release -a x64
    
    # Upload output binaries
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows x64 Stable Build
        path: EFI-Runner/bin/Release/